services:
  - type: web
    name: hospital-bed-management
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
